// This file is automatically generated.

#include <avr/io.h>
#include <util/delay_basic.h>
#include <stdbool.h>

struct list {
    uint8_t size;
    void* values;
};

struct tuple2 {
    void* value0;
    void* value1;
};

struct tuple6 {
    void* value0;
    void* value1;
    void* value2;
    void* value3;
    void* value4;
    void* value5;
};

static void input_timer();

static void stream_1(uint8_t arg, void* value);

static void stream_2(uint8_t arg, void* value);

static void stream_3(uint8_t arg, void* value);

static void stream_4(uint8_t arg, void* value);

static void stream_5(uint8_t arg, void* value);

static void stream_6(uint8_t arg, void* value);

static void stream_8(uint8_t arg, void* value);

static void stream_7(uint8_t arg, void* value);

static void stream_9(uint8_t arg, void* value);

static void stream_10(uint8_t arg, void* value);

static void stream_11(uint8_t arg, void* value);

static void stream_23(uint8_t arg, void* value);

static void stream_12(uint8_t arg, void* value);

static void stream_13(uint8_t arg, void* value);

static void stream_15(uint8_t arg, void* value);

static void stream_14(uint8_t arg, void* value);

static void stream_16(uint8_t arg, void* value);

static void stream_17(uint8_t arg, void* value);

static void stream_18(uint8_t arg, void* value);

static void stream_20(uint8_t arg, void* value);

static void stream_19(uint8_t arg, void* value);

static void stream_21(uint8_t arg, void* value);

static void stream_22(uint8_t arg, void* value);

static void stream_24(uint8_t arg, void* value);

static void stream_25(uint8_t arg, void* value);

static void stream_26(uint8_t arg, void* value);

static void stream_28(uint8_t arg, void* value);

static void stream_27(uint8_t arg, void* value);

static void stream_29(uint8_t arg, void* value);

static void stream_31(uint8_t arg, void* value);

static void stream_30(uint8_t arg, void* value);

static void stream_32(uint8_t arg, void* value);

static void input_timer() {
  uint16_t temp0;
  temp0 = TCNT1;
  TCNT1 = 0;
  stream_1(0, (void*)(&temp0));
}

static void stream_1(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  static uint16_t input_1 = 0;
  uint16_t temp1;
  if ((input_1 > 10000)) {
    temp1 = ((input_1 - 10000) + input_0);
  } else {
    temp1 = (input_1 + input_0);
  }
  input_1 = temp1;
  stream_2(0, (void*)(&input_1));
}

static void stream_2(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  if ((input_0 > 10000)) {
    stream_3(0, (void*)(&input_0));
  }
}

static void stream_3(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  static uint16_t input_1 = 0;
  input_1 = (input_1 + 1);
  stream_4(0, (void*)(&input_1));
}

static void stream_4(uint8_t arg, void* value) {
  uint16_t input_0 = *((uint16_t*)value);
  bool temp2;
  temp2 = (input_0) % 2 == 0;
  stream_5(0, (void*)(&temp2));
}

static void stream_5(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  bool temp3;
  bool temp4;
  struct tuple2 temp5;
  temp3 = input_0;
  temp4 = input_0;
  temp5.value0 = (void*)&temp3;
  temp5.value1 = (void*)&temp4;
  stream_6(0, (void*)(&temp5));
  stream_8(0, (void*)(&temp5));
}

static void stream_6(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_7(0, (void*)(&*((bool*)(input_0).value0)));
}

static void stream_8(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_9(1, (void*)(&*((bool*)(input_0).value1)));
}

static void stream_7(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  bool temp6;
  temp6 = !(input_0);
  stream_9(0, (void*)(&temp6));
}

static void stream_9(uint8_t arg, void* value) {
  static bool input_0;
  static bool input_1;
  bool temp7;
  bool temp8;
  struct tuple2 temp9;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
    case 1:
      input_1 = *((bool*)value);
      break;
  }
  temp7 = input_0;
  temp8 = input_1;
  temp9.value0 = (void*)&temp7;
  temp9.value1 = (void*)&temp8;
  stream_10(0, (void*)(&temp9));
}

static void stream_10(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  bool temp10;
  bool temp11;
  struct tuple2 temp12;
  temp10 = *((bool*)(input_0).value1);
  temp11 = *((bool*)(input_0).value0);
  temp12.value0 = (void*)&temp10;
  temp12.value1 = (void*)&temp11;
  stream_11(0, (void*)(&temp12));
  stream_23(0, (void*)(&temp12));
}

static void stream_11(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_12(0, (void*)(&*((bool*)(input_0).value0)));
}

static void stream_23(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_24(1, (void*)(&*((bool*)(input_0).value1)));
}

static void stream_12(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  bool temp13;
  bool temp14;
  struct tuple2 temp15;
  temp13 = input_0;
  temp14 = input_0;
  temp15.value0 = (void*)&temp13;
  temp15.value1 = (void*)&temp14;
  stream_13(0, (void*)(&temp15));
  stream_15(0, (void*)(&temp15));
}

static void stream_13(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_14(0, (void*)(&*((bool*)(input_0).value0)));
}

static void stream_15(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_16(1, (void*)(&*((bool*)(input_0).value1)));
}

static void stream_14(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  stream_16(0, (void*)(&input_0));
}

static void stream_16(uint8_t arg, void* value) {
  static bool input_0;
  static bool input_1;
  bool temp16;
  bool temp17;
  struct tuple2 temp18;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
    case 1:
      input_1 = *((bool*)value);
      break;
  }
  temp16 = input_0;
  temp17 = input_1;
  temp18.value0 = (void*)&temp16;
  temp18.value1 = (void*)&temp17;
  stream_17(0, (void*)(&temp18));
}

static void stream_17(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  bool temp19;
  bool temp20;
  struct tuple2 temp21;
  temp19 = *((bool*)(input_0).value1);
  temp20 = *((bool*)(input_0).value0);
  temp21.value0 = (void*)&temp19;
  temp21.value1 = (void*)&temp20;
  stream_18(0, (void*)(&temp21));
  stream_20(0, (void*)(&temp21));
}

static void stream_18(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_19(0, (void*)(&*((bool*)(input_0).value0)));
}

static void stream_20(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_21(1, (void*)(&*((bool*)(input_0).value1)));
}

static void stream_19(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  bool temp22;
  temp22 = !(input_0);
  stream_21(0, (void*)(&temp22));
}

static void stream_21(uint8_t arg, void* value) {
  static bool input_0;
  static bool input_1;
  bool temp23;
  bool temp24;
  struct tuple2 temp25;
  switch (arg) {
    case 0:
      input_0 = *((bool*)value);
      break;
    case 1:
      input_1 = *((bool*)value);
      break;
  }
  temp23 = input_0;
  temp24 = input_1;
  temp25.value0 = (void*)&temp23;
  temp25.value1 = (void*)&temp24;
  stream_22(0, (void*)(&temp25));
}

static void stream_22(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  bool temp26;
  bool temp27;
  struct tuple2 temp28;
  temp26 = *((bool*)(input_0).value1);
  temp27 = *((bool*)(input_0).value0);
  temp28.value0 = (void*)&temp26;
  temp28.value1 = (void*)&temp27;
  stream_24(0, (void*)(&temp28));
}

static void stream_24(uint8_t arg, void* value) {
  static struct tuple2 input_0;
  static bool input_1;
  struct tuple2 temp29;
  bool temp30;
  struct tuple2 temp31;
  switch (arg) {
    case 0:
      input_0 = *((struct tuple2*)value);
      break;
    case 1:
      input_1 = *((bool*)value);
      break;
  }
  temp29 = input_0;
  temp30 = input_1;
  temp31.value0 = (void*)&temp29;
  temp31.value1 = (void*)&temp30;
  stream_25(0, (void*)(&temp31));
}

static void stream_25(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  bool temp32;
  struct tuple2 temp33;
  struct tuple2 temp34;
  temp32 = *((bool*)(input_0).value1);
  temp33 = *((struct tuple2*)(input_0).value0);
  temp34.value0 = (void*)&temp32;
  temp34.value1 = (void*)&temp33;
  stream_26(0, (void*)(&temp34));
  stream_28(0, (void*)(&temp34));
}

static void stream_26(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_27(0, (void*)(&*((bool*)(input_0).value0)));
}

static void stream_28(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_29(0, (void*)(&*((struct tuple2*)(input_0).value1)));
  stream_31(0, (void*)(&*((struct tuple2*)(input_0).value1)));
}

static void stream_27(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD3);
  } else {
    PORTD &= ~(1 << PD3);
  }
}

static void stream_29(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_30(0, (void*)(&*((bool*)(input_0).value0)));
}

static void stream_31(uint8_t arg, void* value) {
  struct tuple2 input_0 = *((struct tuple2*)value);
  stream_32(0, (void*)(&*((bool*)(input_0).value1)));
}

static void stream_30(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD4);
  } else {
    PORTD &= ~(1 << PD4);
  }
}

static void stream_32(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD5);
  } else {
    PORTD &= ~(1 << PD5);
  }
}

int main(void) {
  TCCR1B |= (1 << CS12);
  TCCR1B |= (1 << CS10);
  DDRD |= (1 << PD3);
  DDRD |= (1 << PD4);
  DDRD |= (1 << PD5);
  while (1) {
    input_timer();
  }
  return 0;
}
